### ISSUE TITLE
Agent doesn't correctly apply config default values when a non existent path is specified for the config file

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#124]
The agent seems to ignore configuration defaults when a missing config file is specified via the env var `CONFIG_FILE`.

When adjusting default paths for rpm and DEB packages this occurred as the service unit still contained "/etc/stackable-agent/agent.conf".

**Comment by siegfriedweber** [comment]
I cannot reproduce this issue. If I call `CONFIG_FILE=/does_not_exist cargo run --bin stackable-agent` then `AgentConfig` contains the following default values (enriched with `hostname` and `server_ip_address`):

```
AgentConfig {
    hostname: "sigi-desktop",
    parcel_directory: "/opt/stackable/packages",
    config_directory: "/etc/stackable/serviceconfig",
    log_directory: "/var/log/stackable/servicelogs",
    bootstrap_file: "/etc/stackable/stackable-agent/bootstrap-kubelet.conf",
    data_directory: "/var/lib/stackable/agent",
    server_ip_address: 192.168.2.73,
    server_port: 3000,
    server_cert_file: Some("/etc/stackable/stackable-agent/secret/agent.crt"),
    server_key_file: Some("/etc/stackable/stackable-agent/secret/agent.key"),
    tags: {},
    session: false,
    pod_cidr: ""
}
```

**Comment by soenkeliebau** [comment]
Ok, I may very well be mistaken when I noticed this back in the day. Perfectly fine to close this!
