### ISSUE TITLE
Re-evaluate choice of dbus crate

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#139]
We picked dbus-rs for comms with dbus when we go started, which depends on the native libdbus.

Ideally we would want to move to a pure rust implementation which would make the agent binary more universal and easier to build.

There are a couple of libraries that I found:

Library |  Comment
--- |  ---
https://github.com/KillingSpark/rustbus | Seems actively developed, makes no claim to be stable or fully tested yet. Breaking changes are to be expected.
https://gitlab.freedesktop.org/dbus/zbus | Seems actively developed and very well documented. Offers derive macros and high- as well as low-level abstractions.
https://github.com/Arnavion/dbus-pure | Not much documentation, under development, no releases yet afaict.
https://github.com/srwalter/dbus-bytestream| Abandoned

And more, but these seemed like the main ones.

To me zbus looks very promising, but I have not taken an in depth look at any of them yet.

**Comment by siegfriedweber** [comment]
Apart from the listed ones there are no noteworthy native dbus crates. zbus is the most popular one, well-documented, supports everything we need, and is an elegant solution. It seems that it will continue to exist for a while so I would suggest to switch to zbus.
