### ISSUE TITLE
Set invocation ID earlier

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#178]
At the moment the agent only stores the invocation id internally after a service is considered to be successfully started (10 second delay without crashing).

This means that no logs can be retrieved for the first ten seconds of the service's lifetime - never, if the service crashes during that time for some reason.

We should investigate if we can store the invocation id earlier, ideally right after starting the service so that logs can be retrieved during startup as well.

**Comment by lfrancke** [comment]
Made redundant by changes in the agent
