### ISSUE TITLE
Investigate whether we can put our unit files in a separate location from the standard unit files

### ISSUE THREAD

**Issue by soenkeliebau** [stackabletech/agent#8]

**Comment by ohessel** [comment]
Multiple sources tell: 
systemd units may reside wherever they want they just need to be accessible, and be installed by systemctl.
This will create a symlink at the standard path, but we're tidy :-)

`
If the service unit file is not located within one of the known systemd file paths, you can provide a file path to the service unit file you wish to enable:

sudo systemctl enable /path/to/myservice.service

However, this file needs to be accessible by systemd at startup. For example, this means files underneath /home or /var are not allowed, unless those directories are located on the root file system.

`

The most comprehensive source (in addition to the unreadable "standard documentation) can be found here:
https://www.linode.com/docs/guides/introduction-to-systemctl

**Comment by soenkeliebau** [comment]
I've created #37 for this.

**Comment by soenkeliebau** [comment]
I believe the [ADR](https://github.com/stackabletech/documentation/blob/main/adr/ADR004-choose_agent_programming_language.adoc) solves this for now.
